"""Email digest: scheduled email summaries of library activity."""

import uuid
import json
import logging
from datetime import datetime
from fastapi import APIRouter, Depends
from sqlalchemy import text as sa_text

from backend.services.registry import get_db, get_llm_service

logger = logging.getLogger(__name__)
router = APIRouter()


@router.post("/digest-email/generate", summary="Generate email digest content")
async def generate_email_digest(days: int = 7, db=Depends(get_db), llm_service=Depends(get_llm_service)):
    """Generate formatted email digest content."""
    stats = await db.get_processing_stats() if db else {}
    reading_stats = {"to_read": 0, "reading": 0, "read": 0}
    try:
        async with db.async_session_maker() as session:
            row = (await session.execute(sa_text(
                "SELECT COUNT(*), SUM(CASE WHEN status='to_read' THEN 1 ELSE 0 END), SUM(CASE WHEN status='reading' THEN 1 ELSE 0 END), SUM(CASE WHEN status='read' THEN 1 ELSE 0 END) FROM reading_list"))).fetchone()
            if row: reading_stats = {"total": row[0] or 0, "to_read": row[1] or 0, "reading": row[2] or 0, "read": row[3] or 0}
    except: pass

    # Get recent activity
    activity_text = ""
    try:
        async with db.async_session_maker() as session:
            recent = (await session.execute(sa_text(
                "SELECT description, created_at FROM activity_feed ORDER BY created_at DESC LIMIT 5"))).fetchall()
            activity_text = "\n".join([f"  - {r[0]} ({str(r[1])[:10]})" for r in recent])
    except: pass

    # AI-generated research highlight
    highlight = ""
    if llm_service:
        try:
            docs = await db.get_documents(limit=5) if db else []
            if docs:
                titles = "\n".join(f"- {d.title} ({d.year})" for d in docs)
                resp = await llm_service.chat_completion(
                    messages=[{"role": "user", "content": f"Given these papers in a research library, write one paragraph highlighting the most interesting research trend or connection:\n\n{titles}"}],
                    system_prompt="You write concise, insightful research highlights.",
                )
                highlight = resp.get("content", "") if isinstance(resp, dict) else str(resp)
        except: pass

    digest = f"""# Paper Agent Research Digest
**{datetime.utcnow().strftime('%B %d, %Y')}**

## 📊 Library Overview
- **Total Papers**: {stats.get('total', 0)}
- **Processed**: {stats.get('completed', 0)}
- **Reading Progress**: {reading_stats.get('read', 0)} read, {reading_stats.get('reading', 0)} in progress, {reading_stats.get('to_read', 0)} to read

## 🔬 Research Highlight
{highlight or 'No highlight available.'}

## 📖 Recent Activity
{activity_text or 'No recent activity.'}

## 🎯 Reading Queue
Papers waiting for your attention: {reading_stats.get('to_read', 0)}

---
*Generated by Paper Agent*"""

    return {
        "subject": f"Paper Agent Research Digest - {datetime.utcnow().strftime('%b %d, %Y')}",
        "body": digest,
        "stats": {
            "total_papers": stats.get('total', 0),
            "to_read": reading_stats.get('to_read', 0),
            "reading": reading_stats.get('reading', 0),
            "read": reading_stats.get('read', 0),
        },
    }
