"""Overleaf/LaTeX integration API routes."""

import logging
from typing import List, Optional
from fastapi import APIRouter, HTTPException, Depends, Query

from backend.services.registry import get_db
from backend.services.cluster_database import ClusterDatabaseService
from backend.services.citation_service import (
    doc_to_bibtex, generate_bibliography, generate_citation_key,
)

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/bib", summary="Generate .bib file content")
async def generate_bib_file(
    document_ids: str = Query(..., description="Comma-separated document IDs"),
    db: ClusterDatabaseService = Depends(get_db),
):
    """Generate a complete .bib file for use with Overleaf."""
    ids = [did.strip() for did in document_ids.split(",") if did.strip()]
    entries = []

    for did in ids:
        doc = await db.get_document(did)
        if not doc:
            continue
        meta = doc.doc_metadata or {}
        bibtex = doc_to_bibtex(
            doc_id=doc.id, title=doc.title, authors=doc.authors,
            year=doc.year, journal=meta.get("journal"),
            volume=meta.get("volume"), number=meta.get("number"),
            pages=meta.get("pages"), doi=meta.get("doi"),
            url=getattr(doc, "arxiv_url", None),
            abstract=doc.abstract,
        )
        entries.append(bibtex)

    content = "% Generated by Paper Agent\n% https://github.com/KingdeGuo/paper-agent\n\n" + "\n\n".join(entries)
    return {
        "filename": "references.bib",
        "content": content,
        "entry_count": len(entries),
    }


@router.get("/latex-preamble", summary="LaTeX preamble for Paper Agent citations")
async def get_latex_preamble(style: str = "apa"):
    """Generate LaTeX preamble code for citation formatting."""
    style_packages = {
        "apa": r"\usepackage[style=apa]{biblatex}",
        "mla": r"\usepackage[style=mla]{biblatex}",
        "chicago": r"\usepackage[style=chicago-notes]{biblatex}",
        "ieee": r"\usepackage[style=ieee]{biblatex}",
        "harvard": r"\usepackage[style=authoryear]{biblatex}",
    }
    pkg = style_packages.get(style, style_packages["apa"])

    preamble = f"""% Paper Agent - LaTeX Integration
% Add the following to your Overleaf preamble:

{pkg}
\\addbibresource{{references.bib}}

% In the document body, cite with:
% \\cite{{citation_key}} or \\parencite{{citation_key}}

% At the end of the document:
% \\printbibliography
"""
    return {"style": style, "preamble": preamble}


@router.post("/export-for-overleaf", summary="Export documents for Overleaf")
async def export_for_overleaf(
    document_ids: List[str],
    style: str = "apa",
    db: ClusterDatabaseService = Depends(get_db),
):
    """Export documents as a complete Overleaf-ready package."""
    bib_entries = []
    tex_sections = []
    ref_data = []

    for did in document_ids:
        doc = await db.get_document(did)
        if not doc:
            continue
        meta = doc.doc_metadata or {}
        key = generate_citation_key(doc.authors, doc.year, doc.title)

        bib_entries.append(doc_to_bibtex(
            doc_id=doc.id, title=doc.title, authors=doc.authors,
            year=doc.year, journal=meta.get("journal"),
            volume=meta.get("volume"), number=meta.get("number"),
            pages=meta.get("pages"), doi=meta.get("doi"),
            abstract=doc.abstract, key=key,
        ))

        tex_sections.append(f"""% {doc.title}
\\subsection{{{doc.title or 'Untitled'}}}
\\textbf{{{doc.year or 'n.d.'}}} | {', '.join(doc.authors or ['Unknown'])}
\\cite{{{key}}}

{doc.summary or doc.abstract or 'No summary available.'}
""")

        ref_data.append({
            "authors": doc.authors or ["Unknown"], "year": doc.year,
            "title": doc.title or "Untitled", "journal": meta.get("journal", ""),
            "volume": meta.get("volume", ""), "issue": meta.get("number", ""),
            "pages": meta.get("pages", ""), "doi": meta.get("doi", ""),
        })

    bib_content = "% Generated by Paper Agent\n\n" + "\n\n".join(bib_entries)

    style_pkg = {
        "apa": r"\usepackage[style=apa]{biblatex}",
        "mla": r"\usepackage[style=mla]{biblatex}",
        "ieee": r"\usepackage[style=ieee]{biblatex}",
    }.get(style, r"\usepackage[style=authoryear]{biblatex}")

    tex_content = f"""% Overleaf Document - Generated by Paper Agent
% Cite sources using the keys below.

\\documentclass{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{biblatex}}
\\addbibresource{{references.bib}}

\\title{{Literature Review - Generated by Paper Agent}}
\\author{{Paper Agent User}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

{" ".join(tex_sections)}

\\printbibliography
\\end{{document}}
"""

    return {
        "bib_file": {"filename": "references.bib", "content": bib_content},
        "tex_file": {"filename": "main.tex", "content": tex_content},
        "entry_count": len(bib_entries),
        "instructions": "Upload both files to your Overleaf project, then compile with LuaLaTeX or pdfLaTeX.",
    }
